export const SEARCHED_MEDICINE_RESPONSE = 'SEARCHED_MEDICINE_RESPONSE';
export const ALL_MEDICINE_RESPONSE = 'ALL_MEDICINE_RESPONSE';

export const NEW_ADDED_PATIENT = 'NEW_ADDED_PATIENT';
export const ALL_PATIENTS = 'ALL_PATIENTS';

export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_FAILED = 'AUTH_FAILED';
